브런치 확인
wecode-bootcamp-korea/justcode-5-just-gram-react-team-1 pull request #1
Opened 2022-05-25 06:50 UTC by Choi-jeonghoon

2022-05-27 02:48 UTC, Lemonade12 approved these changes

2022-05-27 02:49 UTC, azure928 approved these changes

2022-05-27 04:03 UTC, ssujinc approved these changes

2022-05-27 04:08 UTC, ssujinc requested changes
variables.scss 수정해서 다시 올려주세요~

2022-05-27 04:52 UTC, ssujinc approved these changes

2022-05-28 10:43 UTC, merged

2022-05-30 08:49 UTC, Jtree03 commented on src/pages/jeonghoon/Login/Login.js
> +  const [password, setPassword] = useState("");
https://github.com/wecode-bootcamp-korea/justcode-5-just-gram-react-team-4/pull/5#discussion_r884550026

inputs 관련 참고하시면 되겠습니다.