Feature/ji yook
wecode-bootcamp-korea/justcode-5-just-gram-react-team-1 pull request #6
Opened 2022-05-30 02:48 UTC by azure928

2022-05-30 04:09 UTC, Choi-jeonghoon requested changes
충돌 확인해서 다시한번 pr요청 부탁드립니다.

2022-05-30 05:05 UTC, Choi-jeonghoon requested changes

2022-05-30 05:05 UTC, Choi-jeonghoon commented on src/index.js
> +const root = ReactDOM.createRoot(document.getElementById('root'));
충돌해결부탁드립니다.

2022-05-30 05:05 UTC, Choi-jeonghoon commented on src/pages/jiYook/Login/Login.scss
> +  //top: 50%;
불필요한 주석은 삭제 부탁드립니다.

2022-05-30 05:05 UTC, Choi-jeonghoon commented on src/pages/jiYook/Main/Main.scss
> +    /*background-color: violet;*/
불필요한 주석은 삭제 부탁드립니다.

2022-05-30 05:05 UTC, Choi-jeonghoon commented on src/pages/jiYook/Main/Main.scss
> +    //display: flex;
불필요한 주석은 삭제 부탁드립니다.

2022-05-30 06:53 UTC, Choi-jeonghoon approved these changes

2022-06-01 06:57 UTC, Choi-jeonghoon approved these changes

2022-06-01 08:51 UTC, ssujinc reviewed
Login.scss 와 Main.scss 의 코멘트 확인해주세요
body style 은 공통으로 적용이 돼서, 다시 확인 부탁드립니다.

2022-06-01 08:51 UTC, ssujinc commented on src/pages/jiYook/Login/Login.scss
> +}
공통으로 들어갈수있는 css 입니다. 
다른 식으로 사용해주세요.

2022-06-01 08:51 UTC, ssujinc commented on src/pages/jiYook/Main/Main.scss
> +}
공통으로 들어갈수있는 css 입니다. 
다른 식으로 사용해주세요

2024-03-25 01:36 UTC, closed without merging