Add : Mission 1 ~ 6-1 && css 수정중
wecode-bootcamp-korea/justcode-5-just-gram-react-team-1 pull request #7
Opened 2022-05-30 03:01 UTC by Lemonade12

Add : Mission 1 ~ 6-1 && css 깨져서 수정중

2022-05-30 05:02 UTC, Choi-jeonghoon requested changes
assets/images에 있는 이미지파일을 상민님 폴더에 새로 만들어주세요.

2022-05-30 05:02 UTC, Choi-jeonghoon commented on src/pages/sangmin/Main/Feeds.js
> +            <span className="comment-id">id1</span>
주석처리한부분은 사용안하시는거면 삭제 부탁드려요!

2022-05-30 08:05 UTC, azure928 approved these changes

2022-05-30 08:38 UTC, Choi-jeonghoon approved these changes

2022-05-31 06:59 UTC, ssujinc approved these changes

2022-05-31 07:11 UTC, merged