ADD: 레이아웃 수정 scss 충돌해결
wecode-bootcamp-korea/justcode-5-just-gram-react-team-1 pull request #9
Opened 2022-05-30 08:24 UTC by Choi-jeonghoon

Add: 레이아웃 수정 scss 수정

2022-05-30 08:48 UTC, Jtree03 approved these changes
LGTM~

2022-05-30 08:49 UTC, ssujinc approved these changes

2022-05-30 08:58 UTC, ssujinc requested changes
다 돼었지만, 
login.scss 와 main.scss 도 nesting 해주세요~

2022-05-31 06:54 UTC, Lemonade12 approved these changes

2022-05-31 06:58 UTC, ssujinc approved these changes

2022-05-31 06:58 UTC, merged